---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1szuva9dfevyqqupavutlu6xjp8k6p88kryz3galx554hjt663p2qh594gz"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1szuva9dfevyqqupavutlu6xjp8k6p88kryz3galx554hjt663p2qh594gz"
