apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: fluent-bit
      version: 0.37.0
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    config:
      outputs: |
        [OUTPUT]
            name loki
            match *
            host logs-prod-us-central1.grafana.net
            port 443
            tls on
            tls.verify on
            http_user ${LOKI_HTTP_USER}
            http_passwd ${LOKI_HTTP_PASSWD}
            labels job=fluentbit
            auto_kubernetes_labels on
