---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: proxmox-csi
  namespace: proxmox-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: proxmox-csi-plugin
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    config:
      clusters:
        - url: https://ashe.issei.space:8006/api2/json
          insecure: false
          token_id: "kubernetes-csi@pve!csi"
          token_secret: "${proxmox_kubernetes_csi_secret:=notset}"
          region: Region-1
    storageClass:
      - name: proxmox-data-xfs
        storage: data
        reclaimPolicy: Delete
        fstype: xfs