apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:ci0oqTH1qIDLTtm5kZzAssF79qk=,iv:HxpIpjEvxYdLW9KkbZ/bTMMaVn+g/Qr+wIwF4YgfhnY=,tag:MAHzEGmPmpeNtuUlab9onw==,type:str]
    admin-user: ENC[AES256_GCM,data:Pb7TB6Y=,iv:nROLQFuiTKlG7dnf8XUyUIJMJFfinYB53xjughIq3W4=,tag:S4LL96J9xpl1vATB2vjjuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1szuva9dfevyqqupavutlu6xjp8k6p88kryz3galx554hjt663p2qh594gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2clJhY05NenN6eHpWUVF6
            WkdPUUNoNXJJTklucllPNWVMVWxFSGFJRUc0CmM5VCtYLzlQNnFNWHI2Nk03NXFp
            VUx0Q1RDdWtZNEpIYTR5SjJRbzFXbjgKLS0tIEdMMnV4UklLQ3Y1TC9LYXJ2b3lS
            YTNWMUQramNtSEpPWkFPTXFHOTcyMlUKBQ8iK9iDftbeQW1b/EkQvQnTVAQouCgI
            +KoprHdSpjPrPuGaRI7D2TuHk7sdHRi9sAtkVOd05m5Z2ep2NYpuog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T09:30:34Z"
    mac: ENC[AES256_GCM,data:MbkyNKLpd8ZAphUxgOLShNxjEqc4kLisdYHbt7tpSneIE6rBZ+b6FIJgIzvU/qA36ii3gFjbFwBwo1USPJ+MdGmlQtezkncQAkEB863qvIe0xLmAb2A5ZzJFFH93hj0D6JIvRNRpCttv993zjDfhQBNRM8+3vRJUKpLQrEvIbcI=,iv:QV6R6PB0/Bf7UGO31UlhvWkvctiUchZ+WRQb0UI2ZUI=,tag:+Td/M0O3J9BJDm6iH+lQYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
