apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Q73WAIVwOdG8YPKXkqqbsmUutI6gySRk,iv:CLwJhWiUDIMl65rr1YpmUB/KEyLxgM/yAJSv+5NrXbY=,tag:KOBcW7EGFNBJdtMIDj/sPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1szuva9dfevyqqupavutlu6xjp8k6p88kryz3galx554hjt663p2qh594gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMTc2Rk1BZlh2a0l2eDg1
            a1hXRXdZOUFWQTc4WEZJMnQwNWpiMFRoMzA4CnEvVW1VWmt3d2k5WEREMnlsT2tC
            V2hOOFNzR1RENkx1U2tOR2hIT2pwbnMKLS0tIFVqTldxMXZLTWZsUmN6WUJpWkVh
            VXpRSFg0emR5U3JGcVc3OThEZ1dQNGcK+9btRNQDTV/lU96Mr8FlMvdrd9coNIwA
            nDXqhwCJVQX750UOdDRKp34gjQW6NwRYoRvvtUt3uH5RMlTYmD2cHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T09:30:30Z"
    mac: ENC[AES256_GCM,data:2Hl5b8wzvzh8wbI4pH8NAw8qB/XWWSGCgEG7tOe48iVelUZOUNmXJAdLmSB7lAFRLY+5KkJ2+O+VYWb1VtQW08inxgFudtU1vY5OkyxSziPNE+PfiU+k61AzV6LWDRzmzkPzwqrzO5MJssiLnYwqxxeMCkB2OvjzoKmYXMRevaE=,iv:upPu8CYF2OKWlHd51CrpdjImveJpocDs9UBuMSJ8+Dg=,tag:FoLQ7IU8POtn/5hsOzyI1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
