apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: b2-operator
  namespace: b2-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: backblaze-operator
      sourceRef:
        kind: HelmRepository
        name: isseispace
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    credentials:
      secret:
        useSecret: true
        name: b2operator-credentials
