apiVersion: v1
kind: Secret
metadata:
    name: b2operator-credentials
data:
    B2_APPLICATION_ID: ENC[AES256_GCM,data:KOEWvgMG2PsShcS9,iv:y7yZ6421ugnOee5MfyUw4U+fpCDp2PWtIe5zwr8iX7Y=,tag:eGdma6n/P1DHtu7CtTuYbA==,type:str]
    B2_APPLICATION_KEY: ENC[AES256_GCM,data:pin1wcYrBuWAIpD2AlRZ4mPluqkpVOdqqTvAjban49/+E9HZmdeu/7CH,iv:A74HQQrEexbSj2umxNeM48rw/pnLhbqWwIdnQv6RD9w=,tag:LWmQFBgAwhoPMnppGBtHbQ==,type:str]
    B2_REGION: ENC[AES256_GCM,data:dqnR0D3FtPGVCwg=,iv:JBfrq+4wIlFnjXZCSz0oiMQhlfrGTarLv4KaHDqd9EM=,tag:hIE9sMDBSt90qNn9C2wLKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1szuva9dfevyqqupavutlu6xjp8k6p88kryz3galx554hjt663p2qh594gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVXBwZGdsTEd4bkhDTDFq
            RTgxdW9JZ3FPdWZidGtlbFZaZGlSK1paTkhrCkFST1JKZ1RHRk56bW1lL1lFYWJr
            R05tRkhySEpmVHE1V3dydEEzWkNqcU0KLS0tIEVZQ2M2MlFjdzYyRG5zdGxNVGdi
            T3RVTThVbkxzNHdqRFc0bENqTC9IZTQKI9+m8VvkVhBMS7LFzcHwtwRYS7YK4UIr
            LFa8gcrT/mwkfm3mNwrt81kYqH23gNdmz9ecjiP3Qk49hoihT49WGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-09T20:54:05Z"
    mac: ENC[AES256_GCM,data:ulYKusTpEu1b/PwdiXElb35eDf+UdCPteWqibtVgtgJX0HuzPIcXg8ngalBhOOlcpIz+/Lm3d/U4/Da/gSX0Qrie92D8YLiaDzQy8HT5MooPicvxoHr6wUVH4Wl3DW7/J8vz2tlA2SLSPbXET4kpCqMAgODBPSn8j02DLgM660M=,iv:fG5TyhP8FIMlqYcjQJFft49XxR+/50IYSizsHYD1Wmo=,tag:DqlnDISDQjM5bpXYV8so5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
