apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:oQf8DUfByxv7O2or8tSBPDTlWSsJP8PdSHJ/Kgs/Qy80nxS8IVzuGQ==,iv:1MF1fh7T8gHWiEYJhnIvbVO/sfkDpSd/wY+eoXU28O4=,tag:rkBgniaHXdDKFAnYSMbpHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1szuva9dfevyqqupavutlu6xjp8k6p88kryz3galx554hjt663p2qh594gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aHdWR0t0UVpVbVVIaWtD
            ZjZHTmd6c05CWWVDK0xqa240b2JjWHB0M2hVCmoyS1pKd2VCeUZFdnZ0ZnN0bFN6
            Vkt6QlIvOWszc2RLaXgxeC8zWGJJWTAKLS0tIGlGUXdrTDVIU1JNRlh0NXdxZkg2
            RzZ0aCtPU0d2S3ZlN2NtR3QwbXBTZlEKVeb2U79s4VnLu43y63GNF5yhqF6tx1NG
            Artg5wD6UkwPcKBw7IiATVn9C9ANFxSFDADHQcxNWjdc5b06AxQrkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T09:30:30Z"
    mac: ENC[AES256_GCM,data:d2jFw2xPBPxJW061AuNBr+7zIF7AStmO9IhSirBoFvXwx/PDHMkC1YGwSlIasXHvL4lRNpBkH6FCW3QhWBbHiWvzSU9F1CSy2uWqGO48NOaH7ZHx4eyhbXnoBAE4J65VMemPM4paxOLRqWYPL0g/0xfdVVzBckx7w755CijaWIo=,iv:JTrOTP6E0j6YdcphEDLwNb6KyJm2Bm2UR5kwkdoQiJ0=,tag:lxvHPgi1xFEPyC01B0n1wQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
