---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crossplane
  namespace: flux-system
spec:
  targetNamespace: crossplane-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: postgres-operator
  path: ./kubernetes/apps/crossplane-system/crossplane/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crossplane-provider-sql
  namespace: flux-system
spec:
  targetNamespace: crossplane
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: crossplane
  path: ./kubernetes/apps/crossplane-system/crossplane/provider-sql
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crossplane-provider-config
  namespace: flux-system
spec:
  targetNamespace: crossplane
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: crossplane-provider-sql
  path: ./kubernetes/apps/crossplane-system/crossplane/provider-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m