apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:301ppez1ZoLP+3dXiZaaCdc=,iv:k0GBsStv6Thuam+lkC96R3WE/XfB4SPobeseXNAjOAQ=,tag:5d841MHtYHxB+mXjY5BOvg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:0Gp6sPCr7412xUKP1nO9y2cZ7BLc7mR/EC00vpzVsq+K28kB,iv:2ZfrCbIirlEJdLK0g7X86W333Kpgn5wW+Xn4PpZYawE=,tag:DcaK4nId4LXr11xH91VGIg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:rVcsf7/JO5HPjviFdgk=,iv:MGS+8HAH8Gt8ylgvdWJyklgyt0pB/zKfcH+/B8VQ7wU=,tag:LmypDvGK17Wdr6WwqSqaaA==,type:str]
    LOKI_HTTP_USER: ENC[AES256_GCM,data:3d57WxI=,iv:dpwMmiM64N1Dv8Ck4kex87a6EUO8ajbyZQeAEBeVnHM=,tag:+H8twRp83nSG3KCfOIU1VQ==,type:str]
    LOKI_HTTP_PASSWD: ENC[AES256_GCM,data:5WDCR4viYsbRhL8nH0noFeKELuuCo6x7WSAbrcl3S8Phn7Fa8b4wWbY0dc5uJii5VMFrC0JyUQgH4Vqt8VHO2qDDu6cSb0z1RfGvM4KEl0OlMM4gvLFmnM0AqLadzKm8cGmaxbyGaLA=,iv:WkRKigphNA41sJ0vb/V3XhC3PN5OiXc1tIy0xNXb2Zc=,tag:VdgBxYnDRaLoV/TANWwkqA==,type:str]
    PROXMOX_KUBERNETES_CSI_SECRET: ENC[AES256_GCM,data:gEGKji4wtbNc4n/DTNPSRN2sCAe32IBmR5ayla2dlFVXqPH+,iv:hVbR7HNt5YZHUkx5XVY69l6dzWHWxWHrFc3FHxXq2pY=,tag:bBWS7IGkTl87lpXYyhIiZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1szuva9dfevyqqupavutlu6xjp8k6p88kryz3galx554hjt663p2qh594gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSFBxZFVBbFl1bEFrRUFj
            aDQ0cUtVYTFacElvK3VHVmozUFl4UkZ4dHlZCmRBZUdnaFFYTlJmRkRxeWlDZU9E
            UzhVeWZadm44alR3SEpTQ0JybU4zc1UKLS0tIHN0bDQ3YlV2RHBreXNydTh0ZlRF
            UWtHeldibkVvcW0wQnd6OFQ0Q0RWOXcKxg/HMdeC2c8dcXoDxmaUkGkwBUuh57MQ
            F6Tm6pzCpZj7xK9g9NvqD85d+tqc0nrC1wPUipuMHZtwuvMO99oeSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T19:29:12Z"
    mac: ENC[AES256_GCM,data:EhppmsA2JKIqFiY+6BvrWW9V9p5/91+NLD5sfIHK8UNs2HdWMagcaUOBuf01lExKB45lxGVqL3klHjb0mcU3A0bni5I3WjO2V7OIR4FVt9ZKmiZbsSWXT36T6w/Few2dn+ZOfUv9x65Sm6L3zTc8ZEDdLFv5XIdhOtjyEfEFpVQ=,iv:MnKIkDhEw6UFyeKgxzLcqrdqSDyH4ODTiZjMNoOaAvA=,tag:5SCYiBBL3VQW2En/pCsuzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
