apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:kxDLeW43sUg41ece,iv:gFEllTwCAUFH7L+IdPNAcveZaCeNRKQ/bRz5Cuzzqlc=,tag:QZLFFliNkrNrhV4BZjc4IA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1szuva9dfevyqqupavutlu6xjp8k6p88kryz3galx554hjt663p2qh594gz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRU9Bb01wQkZhVW82S3FD
            SS96Q0R1V3dPRndwcm9UT3RXR1BjWnY5Z2c0ClZTbDRKbi9qVWNYdWhVUzFQc2Ew
            QU9Oa0pYSDVvVmxRRnl2ZjFNaEFuRU0KLS0tIGVPUWpmWTJkL2tuVkg3OXVwUTc2
            WWJMWnhQVGFxVnlUckptL0ZQVzdTOTAKmVGbCHBHsXGXXEDI4shw3Psr2s9z3BL7
            C/BZ//gT1pl/d/PAofBBvA3cc0r/zJNnvqR4J63gXaHj/9sKuKfkxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T09:30:29Z"
    mac: ENC[AES256_GCM,data:tQ0/4Wl3J0NJmGUcKGvQ3JAa+5wwnhA9pNdzPzMRVxc1j2oTVN33Xu6kqBHmZquKAW6dvK1ml2NRgieeJzyuVbT317LKoPO6rU6iGsQOs8WSimf89kcKGTbe+l/1PgvSbsa7aPWUZX1HTLblkMvC1blBAkMl827vEVRBaUBFdmI=,iv:X2cpfb8aMgbb33LfPlKU6mEsvrCkUNBu6iLsQyHJPec=,tag:k3S+DRVPrcfviPqBPu0q8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
